let str = "This is virendra pathak";
// console.log(str.indexOf("a"));
// console.log(str.lastIndexOf("a"));
// console.log(str.slice(1,4));
// console.log(str.substring(1,4));
// console.log(str.substr(1,5));
// console.log(str.split(" "));
// console.log(str.search("vi"));
// console.log(str.match("vi"));
// console.log(str.toString());
console.log(str.matchAll('is'));
